[project]
name = "cp-sheet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "online-judge-tools>=11.5.1",
    "online-judge-verify-helper>=5.6.0",
]

[tool.black]
line_length = 85
