name: KACTL build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Setup pdflatex
        run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra

      - name: Build
        run: |
          cd kactl
          make kactl

      - name: Release PDF
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: kactl/kactl.pdf
