name: KACTL build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Setup pdflatex
        run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra

      - name: Build
        run: |
          cd kactl
          make kactl

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: kactl
          path: kactl/kactl.pdf
